retrieve_news_task:
  description: >
    Search for user reviews about the {topic} using Google.
    Focus on recent comments, pros and cons, and general sentiment.
  expected_output: >
    A summary with:
        - Pros and cons mentioned
        - Overall sentiment (positive, mixed, or negative)
  agent: retrieve_news

review_curator_task:
  description: >
    From the reviews found and analyzed, pick the top 5 most informative ones.
    Ensure variety (not all 5-star or all complaints).
  expected_output: >
    A list of 5 selected reviews, each with:
        - Short quote or paraphrase
        - Source link
        - One-line reason why it was selected
  agent: review_curator

ai_news_write_task:
  description: >
    Summarize the information from the websites into a fully fledge news article in markdown format.
  expected_output: >
    A fully fledge news article with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: ai_news_writer

file_write_task:
  description: >
    Write the news article to a file
  expected_output: >
    A fully fledge news article with all information from previous task into a file named news/{date}_news_article.md
  agent: file_writer
