retrieve_news_task:
  description: >
    Search for user reviews about the {topic} using Google.
    Focus on recent comments, pros and cons, and general sentiment.
  expected_output: >
    A summary with:
        - Top 5 review pages with links
        - Pros and cons mentioned
        - Overall sentiment (positive, mixed, or negative)
  agent: retrieve_news

# website_scrape_task:
#   description: >
#     Scrape the website for the latest news and information
#   expected_output: >
#     Fully scraped websites with all the important information from the website.
#   agent: website_scraper

ai_news_write_task:
  description: >
    Summarize the information from the websites into a fully fledge news article in markdown format.
  expected_output: >
    A fully fledge news article with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: ai_news_writer

file_write_task:
  description: >
    Write the news article to a file
  expected_output: >
    A fully fledge news article with all information from previous task into a file named news/{date}_news_article.md
  agent: file_writer
